# Generated by Django 5.2.11 on 2026-03-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_ex_provider_22f7f7_idx_accounts_ex_provide_c1192a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='inflation_region',
            field=models.CharField(default='ES', max_length=10),
        ),
    ]
