# Generated by Django 5.2.11 on 2026-03-15 11:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("budget", "0012_annualincomeentry_target_month"),
        ("net_worth", "0034_liabilityevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("asset", "Activo"),
                            ("liability", "Pasivo"),
                            ("equity", "Patrimonio neto"),
                            ("income", "Ingreso"),
                            ("expense", "Gasto"),
                        ],
                        max_length=16,
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "origin",
                    models.CharField(
                        choices=[("user", "Usuario"), ("system", "Sistema")],
                        default="user",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_accounts",
                        to="net_worth.asset",
                    ),
                ),
                (
                    "liability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_accounts",
                        to="net_worth.liability",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["account_type", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="LedgerTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("booking_date", models.DateField(default=django.utils.timezone.localdate)),
                ("value_date", models.DateField(default=django.utils.timezone.localdate)),
                ("description", models.CharField(max_length=240)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Borrador"), ("posted", "Contabilizada")],
                        default="posted",
                        max_length=16,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("import", "Importacion"),
                            ("system", "Sistema"),
                        ],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-booking_date", "-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("debit", "Debe"), ("credit", "Haber")], max_length=8
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=20,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("notes", models.CharField(blank=True, default="", max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="accounting.ledgeraccount",
                    ),
                ),
                (
                    "annual_expense_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="budget.annualexpenseentry",
                    ),
                ),
                (
                    "annual_income_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="budget.annualincomeentry",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="net_worth.asset",
                    ),
                ),
                (
                    "liability",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="net_worth.liability",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="accounting.ledgertransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="ledgeraccount",
            index=models.Index(fields=["user", "account_type"], name="acct_acc_user_type_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgeraccount",
            index=models.Index(fields=["user", "is_active"], name="acct_acc_user_active_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(fields=["user", "booking_date"], name="acct_tx_user_book_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(fields=["user", "value_date"], name="acct_tx_user_value_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(fields=["user", "status"], name="acct_tx_user_status_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(fields=["transaction"], name="acct_entry_tx_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(fields=["account"], name="acct_entry_acc_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(fields=["currency"], name="acct_entry_currency_idx"),
        ),
    ]
