# Generated by Django 5.2.11 on 2026-03-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0001_initial"),
        ("budget", "0012_annualincomeentry_target_month"),
        ("net_worth", "0034_liabilityevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgerentry",
            name="category_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="flow_family",
            field=models.CharField(
                blank=True,
                choices=[("income", "Ingreso"), ("expense", "Gasto")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="ledgerentry",
            name="subcategory_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(fields=["flow_family"], name="acct_entry_flow_idx"),
        ),
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(
                fields=["flow_family", "category_key", "subcategory_key"],
                name="acct_entry_class_idx",
            ),
        ),
    ]
