# Generated by Django 5.2.11 on 2026-03-17 22:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0002_ledgerentry_category_key_ledgerentry_flow_family_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgertransaction",
            name="import_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="import_source",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["user", "import_source", "import_fingerprint"],
                name="acct_tx_user_import_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgertransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("import_fingerprint", ""), _negated=True),
                fields=("user", "import_source", "import_fingerprint"),
                name="acct_tx_user_import_fp_unique",
            ),
        ),
    ]
