# Generated by Django 5.2.11 on 2026-03-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_ledgertransaction_import_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgertransaction',
            name='member_tag',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
