# Generated by Django 5.2.11 on 2026-03-23 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0005_ledgertransaction_investment_direction_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ledgertransaction",
            index=models.Index(
                fields=["user", "-booking_date", "-id"], name="acct_tx_user_book_id_desc"
            ),
        ),
    ]
