# Generated by Django 5.2.12 on 2026-04-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_ledgertransaction_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgertransaction',
            name='origin',
            field=models.CharField(choices=[('manual', 'Manual'), ('import', 'Importación'), ('system', 'Sistema')], default='manual', max_length=16),
        ),
    ]
