# Generated by Django 5.2.14 on 2026-05-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0008_alter_ledgertransaction_origin"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ledgerentry",
            index=models.Index(fields=["account", "transaction"], name="acct_entry_acc_tx_idx"),
        ),
    ]
