# Generated by Django 6.0.7 on 2026-08-04 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0010_remove_ledgerentry_annual_expense_entry_and_more"),
        ("budget", "0019_settlementtransferrecommendation_accepted_at_and_more"),
        ("memberships", "0007_ownershipallocationsnapshot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgertransaction",
            name="settlement_action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("application", "Aplicación"),
                    ("reconciliation", "Conciliación"),
                    ("reversal", "Reverso"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="settlement_amount",
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="settlement_idempotency_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="settlement_recommendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_transactions",
                to="budget.settlementtransferrecommendation",
            ),
        ),
        migrations.AddConstraint(
            model_name="ledgertransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("settlement_idempotency_key", ""), _negated=True),
                fields=("user", "settlement_idempotency_key"),
                name="acct_tx_user_settle_key_unique",
            ),
        ),
    ]
