# Generated by Django 6.1 on 2026-08-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0011_ledgertransaction_settlement_action_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgertransaction",
            name="investment_unit_price",
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True),
        ),
        migrations.AddField(
            model_name="ledgertransaction",
            name="investment_units",
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True),
        ),
    ]
