# Generated by Django 6.1 on 2026-08-20 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0012_ledgertransaction_investment_unit_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgertransaction",
            name="fee_for",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_movements",
                to="accounting.ledgertransaction",
            ),
        ),
    ]
