# Generated by Django 6.0.7 on 2026-08-16 20:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounting", "0011_ledgertransaction_settlement_action_and_more"),
        ("memberships", "0007_ownershipallocationsnapshot_and_more"),
        ("net_worth", "0043_alter_assetimprovement_annual_interest_tae"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentContainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "container_type",
                    models.CharField(
                        choices=[
                            ("broker", "Broker"),
                            ("bank", "Banco"),
                            ("exchange", "Exchange"),
                            ("wallet", "Wallet"),
                            ("pension", "Plan de pensiones"),
                            ("platform", "Plataforma"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "identity_kind",
                    models.CharField(
                        choices=[("custom", "Custom"), ("canonical", "Canónico")], max_length=16
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("fixed_income", "Renta fija"),
                            ("equity", "Renta variable"),
                            ("mixed", "Mixto"),
                            ("real_assets", "Activos reales"),
                            ("crypto", "Cripto"),
                            ("other", "Otros"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "instrument_type",
                    models.CharField(
                        choices=[
                            ("cash", "Efectivo"),
                            ("deposit", "Depósito"),
                            ("fund", "Fondo"),
                            ("etf", "ETF"),
                            ("stock", "Acción"),
                            ("pension_plan", "Plan de pensiones"),
                            ("crypto", "Criptoactivo"),
                            ("crowdfunding", "Crowdfunding"),
                            ("other", "Otros"),
                        ],
                        max_length=24,
                    ),
                ),
                ("quote_currency", models.CharField(max_length=3)),
                ("isin", models.CharField(blank=True, default="", max_length=12)),
                ("ticker", models.CharField(blank=True, default="", max_length=32)),
                ("market", models.CharField(blank=True, default="", max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null para instrumentos canónicos compartidos.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_instruments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContainerCashAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ledger_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_cash_link",
                        to="accounting.ledgeraccount",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_accounts",
                        to="portfolio.investmentcontainer",
                    ),
                ),
            ],
            options={
                "ordering": ["currency", "id"],
            },
        ),
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("base_currency", models.CharField(default="EUR", max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="investmentcontainer",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="containers",
                to="portfolio.portfolio",
            ),
        ),
        migrations.CreateModel(
            name="PortfolioMigrationIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("ledger_account_missing", "Cuenta contable ausente"),
                            ("ledger_account_ambiguous", "Cuenta contable ambigua"),
                            ("ownership_missing", "Titularidad ausente"),
                            ("ownership_dynamic", "Titularidad dinámica"),
                            ("ownership_shares_invalid", "Reparto inválido"),
                            ("bootstrap_error", "Error de migración"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Pendiente"), ("resolved", "Resuelta")],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("detail", models.CharField(blank=True, default="", max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_migration_issues",
                        to="net_worth.asset",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="migration_issues",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_id", "code"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tracking_style",
                    models.CharField(
                        choices=[("value_based", "Por valor"), ("units_based", "Por unidades")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Activa"), ("archived", "Archivada")], max_length=16
                    ),
                ),
                ("opened_on", models.DateField()),
                ("closed_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_position",
                        to="net_worth.asset",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="portfolio.investmentcontainer",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="positions",
                        to="portfolio.instrument",
                    ),
                ),
                (
                    "ledger_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_positions",
                        to="accounting.ledgeraccount",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["instrument__name", "id"],
            },
        ),
        migrations.CreateModel(
            name="PositionOwnershipPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ownership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_ownership_periods",
                        to="memberships.ownership",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_periods",
                        to="portfolio.portfolioposition",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="PositionOwnershipShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_ownership_shares",
                        to="memberships.familymember",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shares",
                        to="portfolio.positionownershipperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["member_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="instrument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("identity_kind", "canonical"), ("user__isnull", True)),
                    models.Q(("identity_kind", "custom"), ("user__isnull", False)),
                    _connector="OR",
                ),
                name="portfolio_instrument_identity_owner_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="instrument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identity_kind", "custom")),
                fields=("user", "name", "quote_currency"),
                name="portfolio_custom_instrument_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="instrument",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("identity_kind", "canonical"), models.Q(("isin", ""), _negated=True)
                ),
                fields=("isin",),
                name="portfolio_canonical_isin_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="containercashaccount",
            constraint=models.UniqueConstraint(
                fields=("container", "currency"), name="portfolio_container_cash_currency_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="investmentcontainer",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "name"), name="portfolio_container_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliomigrationissue",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "asset", "code"), name="portfolio_migration_issue_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="portfolioposition",
            index=models.Index(fields=["portfolio", "status"], name="portfolio_pos_status_idx"),
        ),
        migrations.AddIndex(
            model_name="portfolioposition",
            index=models.Index(fields=["container", "status"], name="portfolio_pos_container_idx"),
        ),
        migrations.AddConstraint(
            model_name="portfolioposition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("closed_on__isnull", True),
                    ("closed_on__gte", models.F("opened_on")),
                    _connector="OR",
                ),
                name="portfolio_position_dates_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="positionownershipperiod",
            constraint=models.UniqueConstraint(
                fields=("position", "start_date"), name="portfolio_ownership_period_start_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="positionownershipperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="portfolio_ownership_period_dates_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="positionownershipshare",
            constraint=models.UniqueConstraint(
                fields=("period", "member"), name="portfolio_ownership_share_member_unique"
            ),
        ),
    ]
