# Generated by Django 6.0.7 on 2026-08-16 20:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_bootstrap_existing_investments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="instrument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("identity_kind", "custom"),
                    models.Q(("isin", ""), _negated=True),
                    models.Q(
                        models.Q(("ticker", ""), _negated=True),
                        models.Q(("market", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="portfolio_canonical_identity_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="instrument",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("identity_kind", "canonical"),
                    models.Q(("ticker", ""), _negated=True),
                    models.Q(("market", ""), _negated=True),
                ),
                fields=("ticker", "market"),
                name="portfolio_canonical_ticker_market_unique",
            ),
        ),
    ]
