# Generated by Django 6.0.7 on 2026-08-16 20:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("net_worth", "0043_alter_assetimprovement_annual_interest_tae"),
        ("portfolio", "0003_instrument_portfolio_canonical_identity_required_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstrumentProviderMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("twelve_data", "Twelve Data"), ("coingecko", "CoinGecko")],
                        max_length=24,
                    ),
                ),
                ("provider_symbol", models.CharField(max_length=96)),
                ("provider_market", models.CharField(blank=True, default="", max_length=32)),
                ("quote_currency", models.CharField(max_length=3)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provider_mappings",
                        to="portfolio.instrument",
                    ),
                ),
            ],
            options={
                "ordering": ["instrument_id", "provider"],
            },
        ),
        migrations.CreateModel(
            name="InstrumentPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("price_date", models.DateField()),
                (
                    "close",
                    models.DecimalField(
                        decimal_places=12,
                        max_digits=28,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("source", models.CharField(max_length=32)),
                ("source_key", models.CharField(max_length=128)),
                ("source_market", models.CharField(blank=True, default="", max_length=32)),
                ("fetched_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="portfolio.instrument",
                    ),
                ),
                (
                    "provider_mapping",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prices",
                        to="portfolio.instrumentprovidermapping",
                    ),
                ),
            ],
            options={
                "ordering": ["-price_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PositionValuation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("valuation_date", models.DateField()),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=28,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("legacy_asset", "Derivada de AssetValuation"),
                        ],
                        default="manual",
                        max_length=24,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legacy_asset_valuation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_derived_valuation",
                        to="net_worth.assetvaluation",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_valuations",
                        to="portfolio.portfolioposition",
                    ),
                ),
            ],
            options={
                "ordering": ["-valuation_date", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="instrumentprovidermapping",
            constraint=models.UniqueConstraint(
                fields=("instrument", "provider", "quote_currency"),
                name="portfolio_instrument_provider_quote_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="instrumentprovidermapping",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_confirmed", False), ("confirmed_at__isnull", False), _connector="OR"
                ),
                name="portfolio_confirmed_mapping_has_timestamp",
            ),
        ),
        migrations.AddIndex(
            model_name="instrumentprice",
            index=models.Index(
                fields=["instrument", "price_date"], name="portfolio_price_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="instrumentprice",
            constraint=models.UniqueConstraint(
                fields=("instrument", "price_date", "source", "source_key"),
                name="portfolio_instrument_price_source_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="positionvaluation",
            index=models.Index(
                fields=["position", "valuation_date"], name="portfolio_valuation_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="positionvaluation",
            constraint=models.UniqueConstraint(
                fields=("position", "valuation_date", "source"),
                name="portfolio_position_valuation_source_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="positionvaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("legacy_asset_valuation__isnull", False), ("source", "legacy_asset")),
                    models.Q(("legacy_asset_valuation__isnull", True), ("source", "manual")),
                    _connector="OR",
                ),
                name="portfolio_position_valuation_source_valid",
            ),
        ),
    ]
