# Generated by Django 6.0.7 on 2026-08-16 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0011_ledgertransaction_settlement_action_and_more"),
        ("net_worth", "0043_alter_assetimprovement_annual_interest_tae"),
        ("portfolio", "0005_import_legacy_valuations_and_crypto_mappings"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="positionvaluation",
            name="portfolio_position_valuation_source_valid",
        ),
        migrations.AddField(
            model_name="positionvaluation",
            name="legacy_ledger_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portfolio_derived_valuations",
                to="accounting.ledgertransaction",
            ),
        ),
        migrations.AlterField(
            model_name="positionvaluation",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("legacy_asset", "Derivada de AssetValuation"),
                    ("legacy_ledger", "Derivada de revalorización contable"),
                ],
                default="manual",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="positionvaluation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("legacy_asset_valuation__isnull", False),
                        ("legacy_ledger_transaction__isnull", True),
                        ("source", "legacy_asset"),
                    ),
                    models.Q(
                        ("legacy_asset_valuation__isnull", True),
                        ("legacy_ledger_transaction__isnull", False),
                        ("source", "legacy_ledger"),
                    ),
                    models.Q(
                        ("legacy_asset_valuation__isnull", True),
                        ("legacy_ledger_transaction__isnull", True),
                        ("source", "manual"),
                    ),
                    _connector="OR",
                ),
                name="portfolio_position_valuation_source_valid",
            ),
        ),
    ]
