# Generated by Django 6.0.7 on 2026-08-17 05:08

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0011_ledgertransaction_settlement_action_and_more"),
        ("portfolio", "0007_import_ledger_revaluation_history"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioCorporateAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("split", "Split / contrasplit"),
                            ("identifier_change", "Cambio de identificador"),
                            ("position_transfer", "Traspaso entre posiciones"),
                            ("adjustment", "Ajuste manual"),
                        ],
                        max_length=32,
                    ),
                ),
                ("effective_date", models.DateField()),
                ("payload", models.JSONField(default=dict)),
                ("note", models.CharField(blank=True, default="", max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ledger_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_corporate_action",
                        to="accounting.ledgertransaction",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporate_actions",
                        to="portfolio.portfolio",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="corporate_actions",
                        to="portfolio.portfolioposition",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("filename", models.CharField(max_length=240)),
                ("file_fingerprint", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Subido"),
                            ("previewed", "Previsualizado"),
                            ("partial", "Confirmado parcialmente"),
                            ("confirmed", "Confirmado"),
                            ("failed", "Fallido"),
                        ],
                        default="uploaded",
                        max_length=16,
                    ),
                ),
                ("headers", models.JSONField(default=list)),
                ("mapping", models.JSONField(default=dict)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("confirmed_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_batches",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("buy", "Compra"),
                            ("sell", "Venta"),
                            ("dividend", "Dividendo"),
                            ("interest", "Interés"),
                            ("fee", "Comisión"),
                            ("funded_purchase", "Compra histórica financiada"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "units",
                    models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True),
                ),
                (
                    "unit_price",
                    models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True),
                ),
                ("trade_currency", models.CharField(max_length=3)),
                ("gross_amount", models.DecimalField(decimal_places=8, max_digits=28)),
                ("fee", models.DecimalField(decimal_places=8, default=Decimal("0"), max_digits=28)),
                ("external_id", models.CharField(blank=True, default="", max_length=160)),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Manual"), ("csv", "CSV"), ("legacy", "Histórico")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64)),
                ("note", models.CharField(blank=True, default="", max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fee_transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_trade_fee",
                        to="accounting.ledgertransaction",
                    ),
                ),
                (
                    "ledger_transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_trade",
                        to="accounting.ledgertransaction",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="portfolio.portfolio",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trades",
                        to="portfolio.portfolioposition",
                    ),
                ),
            ],
            options={
                "ordering": ["-ledger_transaction__booking_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioImportRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("row_number", models.PositiveIntegerField()),
                ("raw_data", models.JSONField(default=dict)),
                ("normalized_data", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("valid", "Válida"),
                            ("error", "Con errores"),
                            ("duplicate", "Duplicada"),
                            ("confirmed", "Confirmada"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("errors", models.JSONField(default=dict)),
                ("fingerprint", models.CharField(blank=True, default="", max_length=64)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="portfolio.portfolioimportbatch",
                    ),
                ),
                (
                    "trade",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_row",
                        to="portfolio.portfoliotrade",
                    ),
                ),
            ],
            options={
                "ordering": ["row_number"],
            },
        ),
        migrations.AddConstraint(
            model_name="portfolioimportbatch",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "file_fingerprint"), name="portfolio_import_file_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliotrade",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("portfolio", "source", "external_id"),
                name="portfolio_trade_external_source_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="portfoliotrade",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "fingerprint"), name="portfolio_trade_fingerprint_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="portfolioimportrow",
            constraint=models.UniqueConstraint(
                fields=("batch", "row_number"), name="portfolio_import_row_number_unique"
            ),
        ),
    ]
