# Generated by Django 6.0.7 on 2026-08-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0011_ledgertransaction_settlement_action_and_more"),
        ("net_worth", "0043_alter_assetimprovement_annual_interest_tae"),
        ("portfolio", "0008_portfoliocorporateaction_portfolioimportbatch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioposition",
            name="history_mode",
            field=models.CharField(
                choices=[
                    ("reconstructed", "Histórico reconstruido"),
                    ("cutoff", "Inicio desde fecha de corte"),
                ],
                default="reconstructed",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="portfolioposition",
            name="history_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfolioposition",
            name="setup_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="portfolioposition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("history_mode", "reconstructed"), ("history_start_date__isnull", True)
                    ),
                    models.Q(("history_mode", "cutoff"), ("history_start_date__isnull", False)),
                    _connector="OR",
                ),
                name="portfolio_position_history_mode_valid",
            ),
        ),
    ]
