# Generated by Django 6.1 on 2026-08-17 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0011_ledgertransaction_settlement_action_and_more"),
        ("portfolio", "0009_portfolioposition_history_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positionvaluation",
            name="legacy_ledger_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_derived_valuations",
                to="accounting.ledgertransaction",
            ),
        ),
    ]
