# Generated by Django 6.1 on 2026-08-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0011_alter_instrument_asset_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioposition",
            name="asset_class_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fixed_income", "Renta fija"),
                    ("equity", "Renta variable"),
                    ("real_estate", "Inmobiliario"),
                    ("private_equity", "Capital privado"),
                    ("safe_haven", "Activos refugio"),
                    ("commodities", "Materias primas"),
                    ("alternatives", "Inversiones alternativas"),
                    ("trading", "Trading"),
                    ("opportunity_cash", "Liquidez para oportunidades"),
                    ("other", "Otros"),
                ],
                default="",
                max_length=24,
            ),
        ),
    ]
