# Generated by Django 6.1 on 2026-08-18 20:12

from django.db import migrations, models

# Los tres ejes que la taxonomía anterior mezclaba en un solo campo vuelven a su sitio.
# "Activos refugio" era un rol y juntaba oro con criptomonedas, que se comportan al
# revés, así que se separa por el tipo de instrumento, que sí lo sabe. "Trading" era una
# estrategia y "Liquidez para oportunidades" un propósito.
FORWARD = {
    "opportunity_cash": "cash",
    "trading": "other",
    "alternatives": "other",
    "safe_haven": "commodities",
}
BACKWARD = {
    "cash": "opportunity_cash",
    "crypto": "safe_haven",
    "private_debt": "fixed_income",
}


def _remap(apps, owner, field, mapping):
    model = apps.get_model("portfolio", owner)
    for old, new in mapping.items():
        model.objects.filter(**{field: old}).update(**{field: new})


def forwards(apps, schema_editor):
    _remap(apps, "Instrument", "asset_class", FORWARD)
    _remap(apps, "PortfolioPosition", "asset_class_override", FORWARD)
    # El oro se queda en materias primas; lo que era refugio y es criptoactivo pasa a su
    # clase propia, que es la que describe cómo se comporta.
    instruments = apps.get_model("portfolio", "Instrument").objects
    positions = apps.get_model("portfolio", "PortfolioPosition").objects
    instruments.filter(asset_class="commodities", instrument_type="crypto").update(
        asset_class="crypto"
    )
    positions.filter(
        asset_class_override="commodities", instrument__instrument_type="crypto"
    ).update(asset_class_override="crypto")
    # El crowdlending es crédito con riesgo de impago: ni renta fija cotizada, ni el
    # cajón de "alternativas" donde acababa por no haber sitio mejor.
    instruments.filter(
        asset_class__in=["other", "fixed_income"], instrument_type="crowdfunding"
    ).update(asset_class="private_debt")
    positions.filter(
        asset_class_override__in=["other", "fixed_income"],
        instrument__instrument_type="crowdfunding",
    ).update(asset_class_override="private_debt")


def backwards(apps, schema_editor):
    _remap(apps, "Instrument", "asset_class", BACKWARD)
    _remap(apps, "PortfolioPosition", "asset_class_override", BACKWARD)


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0012_portfolioposition_asset_class_override"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        migrations.AlterField(
            model_name="instrument",
            name="asset_class",
            field=models.CharField(
                choices=[
                    ("equity", "Renta variable"),
                    ("fixed_income", "Renta fija"),
                    ("real_estate", "Inmobiliario"),
                    ("private_debt", "Deuda privada"),
                    ("commodities", "Materias primas"),
                    ("private_equity", "Capital privado"),
                    ("crypto", "Criptoactivos"),
                    ("cash", "Liquidez"),
                    ("other", "Otros"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioposition",
            name="asset_class_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equity", "Renta variable"),
                    ("fixed_income", "Renta fija"),
                    ("real_estate", "Inmobiliario"),
                    ("private_debt", "Deuda privada"),
                    ("commodities", "Materias primas"),
                    ("private_equity", "Capital privado"),
                    ("crypto", "Criptoactivos"),
                    ("cash", "Liquidez"),
                    ("other", "Otros"),
                ],
                default="",
                max_length=24,
            ),
        ),
    ]
