# Generated by Django 6.1 on 2026-08-18 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0013_alter_instrument_asset_class_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionClassBreakdown",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("equity", "Renta variable"),
                            ("fixed_income", "Renta fija"),
                            ("real_estate", "Inmobiliario"),
                            ("private_debt", "Deuda privada"),
                            ("commodities", "Materias primas"),
                            ("private_equity", "Capital privado"),
                            ("crypto", "Criptoactivos"),
                            ("cash", "Liquidez"),
                            ("other", "Otros"),
                        ],
                        max_length=24,
                    ),
                ),
                ("percent", models.DecimalField(decimal_places=3, max_digits=6)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_breakdown",
                        to="portfolio.portfolioposition",
                    ),
                ),
            ],
            options={
                "ordering": ["-percent", "asset_class"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("position", "asset_class"), name="portfolio_class_breakdown_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("percent__gt", 0), ("percent__lte", 100)),
                        name="portfolio_class_breakdown_percent_range",
                    ),
                ],
            },
        ),
    ]
