# Generated by Django 6.1 on 2026-08-19 06:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


# Un fondo de inversion y un plan de pensiones admiten traspaso sin peaje fiscal en
# Espana; un ETF, una accion, una cripto o una plataforma de crowdfunding, no. El tipo de
# instrumento lo sabe, asi que el arranque no deja el dato en blanco esperando a que
# alguien lo rellene posicion por posicion. Es un punto de partida editable, no una
# verdad fiscal: hay fondos no traspasables y el usuario manda sobre el flag.
TRANSFERABLE_TYPES = ["fund", "pension_plan"]


def set_transferable_defaults(apps, schema_editor):
    apps.get_model("portfolio", "PortfolioPosition").objects.filter(
        instrument__instrument_type__in=TRANSFERABLE_TYPES
    ).update(tax_transferable=True)


def clear_transferable(apps, schema_editor):
    apps.get_model("portfolio", "PortfolioPosition").objects.update(tax_transferable=False)


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0007_ownershipallocationsnapshot_and_more"),
        ("portfolio", "0015_reclassify_commodities_from_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioposition",
            name="tax_transferable",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="AllocationStrategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("effective_from", models.DateField()),
                ("note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ownership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_strategies",
                        to="memberships.ownership",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_strategies",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AllocationTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "asset_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("equity", "Renta variable"),
                            ("fixed_income", "Renta fija"),
                            ("real_estate", "Inmobiliario"),
                            ("private_debt", "Deuda privada"),
                            ("commodities", "Materias primas"),
                            ("private_equity", "Capital privado"),
                            ("crypto", "Criptoactivos"),
                            ("cash", "Liquidez"),
                            ("other", "Otros"),
                        ],
                        default="",
                        max_length=24,
                    ),
                ),
                (
                    "target_percent",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "min_percent",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
                ),
                (
                    "max_percent",
                    models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_targets",
                        to="portfolio.portfolioposition",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="portfolio.allocationstrategy",
                    ),
                ),
            ],
            options={
                "ordering": ["-target_percent", "asset_class", "id"],
            },
        ),
        migrations.CreateModel(
            name="PositionAllocationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("excluded", models.BooleanField(default=False)),
                (
                    "min_contribution",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "rounding_step",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "position",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocation_rule",
                        to="portfolio.portfolioposition",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="allocationstrategy",
            index=models.Index(
                fields=["portfolio", "ownership", "effective_from"],
                name="portfolio_a_portfol_992909_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationstrategy",
            constraint=models.UniqueConstraint(
                fields=("portfolio", "ownership", "effective_from"),
                name="portfolio_strategy_version_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationtarget",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("asset_class", ""), ("position__isnull", False)),
                    models.Q(
                        models.Q(("asset_class", ""), _negated=True), ("position__isnull", True)
                    ),
                    _connector="OR",
                ),
                name="portfolio_target_one_level_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationtarget",
            constraint=models.CheckConstraint(
                condition=models.Q(("target_percent__gte", 0), ("target_percent__lte", 100)),
                name="portfolio_target_percent_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationtarget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("asset_class", ""), _negated=True),
                fields=("strategy", "asset_class"),
                name="portfolio_target_class_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="allocationtarget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("position__isnull", False)),
                fields=("strategy", "position"),
                name="portfolio_target_position_unique",
            ),
        ),
        migrations.RunPython(set_transferable_defaults, clear_transferable),
    ]
