# Generated by Django 6.1 on 2026-08-19 08:11

from django.db import migrations, models


# Los instrumentos que cayeron en "Otros" por defecto pasan a "Sin clasificar", pero solo
# aquellos cuya subcategoria no determina la clase: en cripto o crowdlending el vehiculo
# ya la dice, asi que un "Otros" ahi lo puso una persona a proposito y se respeta. Un
# fondo, un ETF, un plan o un roboadvisor pueden ser cualquier cosa, y ahi "Otros" era el
# valor por defecto disfrazado de respuesta.
DETERMINED_BY_SUBCATEGORY = [
    "deposits",
    "stocks",
    "cryptocurrencies",
    "real_estate_crowd",
    "crowdlending",
]


def mark_undecided(apps, schema_editor):
    positions = apps.get_model("portfolio", "PortfolioPosition").objects.select_related(
        "asset", "instrument"
    )
    instrument_ids = [
        position.instrument_id
        for position in positions
        if position.instrument.asset_class == "other"
        and position.asset.subcategory not in DETERMINED_BY_SUBCATEGORY
    ]
    if instrument_ids:
        apps.get_model("portfolio", "Instrument").objects.filter(id__in=instrument_ids).update(
            asset_class="unclassified"
        )


def back_to_other(apps, schema_editor):
    for model, field in (
        ("Instrument", "asset_class"),
        ("PortfolioPosition", "asset_class_override"),
    ):
        apps.get_model("portfolio", model).objects.filter(**{field: "unclassified"}).update(
            **{field: "other"}
        )


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0016_portfolioposition_tax_transferable_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocationtarget",
            name="asset_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equity", "Renta variable"),
                    ("fixed_income", "Renta fija"),
                    ("real_estate", "Inmobiliario"),
                    ("private_debt", "Deuda privada"),
                    ("commodities", "Materias primas"),
                    ("private_equity", "Capital privado"),
                    ("crypto", "Criptoactivos"),
                    ("cash", "Liquidez"),
                    ("other", "Otros"),
                    ("unclassified", "Sin clasificar"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="instrument",
            name="asset_class",
            field=models.CharField(
                choices=[
                    ("equity", "Renta variable"),
                    ("fixed_income", "Renta fija"),
                    ("real_estate", "Inmobiliario"),
                    ("private_debt", "Deuda privada"),
                    ("commodities", "Materias primas"),
                    ("private_equity", "Capital privado"),
                    ("crypto", "Criptoactivos"),
                    ("cash", "Liquidez"),
                    ("other", "Otros"),
                    ("unclassified", "Sin clasificar"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioposition",
            name="asset_class_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("equity", "Renta variable"),
                    ("fixed_income", "Renta fija"),
                    ("real_estate", "Inmobiliario"),
                    ("private_debt", "Deuda privada"),
                    ("commodities", "Materias primas"),
                    ("private_equity", "Capital privado"),
                    ("crypto", "Criptoactivos"),
                    ("cash", "Liquidez"),
                    ("other", "Otros"),
                    ("unclassified", "Sin clasificar"),
                ],
                default="",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="positionclassbreakdown",
            name="asset_class",
            field=models.CharField(
                choices=[
                    ("equity", "Renta variable"),
                    ("fixed_income", "Renta fija"),
                    ("real_estate", "Inmobiliario"),
                    ("private_debt", "Deuda privada"),
                    ("commodities", "Materias primas"),
                    ("private_equity", "Capital privado"),
                    ("crypto", "Criptoactivos"),
                    ("cash", "Liquidez"),
                    ("other", "Otros"),
                    ("unclassified", "Sin clasificar"),
                ],
                max_length=24,
            ),
        ),
        migrations.RunPython(mark_undecided, back_to_other),
    ]
