# Generated by Django 6.1 on 2026-08-19 09:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0017_alter_allocationtarget_asset_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="positionallocationrule",
            name="fee_free_plan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="positionallocationrule",
            name="operation_cost",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
        ),
        migrations.CreateModel(
            name="ContributionCommitment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[("month", "Mensual"), ("year", "Anual")], max_length=8
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commitments",
                        to="portfolio.portfolioposition",
                    ),
                ),
            ],
            options={
                "ordering": ["position_id", "period"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("position", "period"), name="portfolio_commitment_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="portfolio_commitment_amount_positive",
                    ),
                ],
            },
        ),
    ]
