# Generated by Django 6.1 on 2026-08-19 09:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0018_positionallocationrule_fee_free_plan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationstrategy",
            name="max_cost_share",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.005"),
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
    ]
