# Generated by Django 6.1 on 2026-08-19 10:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0012_ledgertransaction_investment_unit_price_and_more"),
        ("memberships", "0007_ownershipallocationsnapshot_and_more"),
        ("portfolio", "0019_allocationstrategy_max_cost_share"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributionBasket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("booking_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "reserved_cash",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "leftover",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("discarded", "Descartada"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("explanation", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ownership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contribution_baskets",
                        to="memberships.ownership",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution_baskets",
                        to="portfolio.portfolio",
                    ),
                ),
                (
                    "source_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portfolio_baskets",
                        to="accounting.ledgeraccount",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baskets",
                        to="portfolio.allocationstrategy",
                    ),
                ),
            ],
            options={
                "ordering": ["-booking_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ContributionBasketLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("reason", models.CharField(blank=True, default="", max_length=32)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("confirmed", "Confirmada"),
                            ("skipped", "Descartada"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="portfolio.contributionbasket",
                    ),
                ),
                (
                    "cash_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basket_lines",
                        to="portfolio.containercashaccount",
                    ),
                ),
                (
                    "ledger_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_basket_lines",
                        to="accounting.ledgertransaction",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="basket_lines",
                        to="portfolio.portfolioposition",
                    ),
                ),
            ],
            options={
                "ordering": ["-amount", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="contributionbasket",
            index=models.Index(
                fields=["portfolio", "status"], name="portfolio_c_portfol_319b15_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contributionbasket",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="portfolio_basket_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="contributionbasketline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("cash_account__isnull", True), ("position__isnull", False)),
                    models.Q(("cash_account__isnull", False), ("position__isnull", True)),
                    _connector="OR",
                ),
                name="portfolio_basket_line_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="contributionbasketline",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="portfolio_basket_line_amount_positive"
            ),
        ),
    ]
