# Generated by Django 6.1 on 2026-08-19 10:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0020_contributionbasket_contributionbasketline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationstrategy",
            name="min_line_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
        ),
    ]
