# Generated by Django 6.1 on 2026-08-20 09:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0022_alter_allocationtarget_asset_class_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contributioncommitment",
            name="breach_cost",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
        ),
        migrations.AddConstraint(
            model_name="contributioncommitment",
            constraint=models.CheckConstraint(
                condition=models.Q(("breach_cost__gte", 0)),
                name="portfolio_commitment_breach_cost_positive",
            ),
        ),
    ]
