# Generated by Django 6.1 on 2026-08-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0024_alter_contributioncommitment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionExposure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("geography", "Geografía"),
                            ("sector", "Sector"),
                            ("vehicle", "Vehículo"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "bucket",
                    models.CharField(
                        choices=[
                            ("north_america", "Norteamérica"),
                            ("europe", "Europa"),
                            ("spain", "España"),
                            ("japan", "Japón"),
                            ("asia_pacific", "Asia-Pacífico"),
                            ("emerging", "Emergentes"),
                            ("global", "Global"),
                            ("technology", "Tecnología"),
                            ("financials", "Financiero"),
                            ("health_care", "Salud"),
                            ("consumer_discretionary", "Consumo discrecional"),
                            ("consumer_staples", "Consumo básico"),
                            ("industrials", "Industrial"),
                            ("energy", "Energía"),
                            ("materials", "Materiales"),
                            ("utilities", "Servicios públicos"),
                            ("real_estate_sector", "Inmobiliario"),
                            ("communication", "Comunicación"),
                            ("index_fund", "Fondo indexado"),
                            ("active_fund", "Fondo activo"),
                            ("etf", "ETF"),
                            ("pension_plan", "Plan de pensiones"),
                            ("direct_equity", "Acciones directas"),
                            ("crowdfunding", "Crowdfunding"),
                            ("crypto", "Criptoactivo"),
                            ("deposit", "Depósito"),
                            ("other", "Otros"),
                        ],
                        max_length=32,
                    ),
                ),
                ("percent", models.DecimalField(decimal_places=3, max_digits=6)),
                ("observed_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exposures",
                        to="portfolio.portfolioposition",
                    ),
                ),
            ],
            options={
                "ordering": ["dimension", "-percent", "bucket"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("position", "dimension", "bucket"), name="portfolio_exposure_unique"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("percent__gt", 0), ("percent__lte", 100)),
                        name="portfolio_exposure_percent_range",
                    ),
                ],
            },
        ),
    ]
