# Generated by Django 6.1 on 2026-08-20 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0013_ledgertransaction_fee_for"),
        ("portfolio", "0027_seed_etf_exposure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliotrade",
            name="fee_transaction",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portfolio_trade_fee",
                to="accounting.ledgertransaction",
            ),
        ),
        migrations.AlterField(
            model_name="portfoliotrade",
            name="ledger_transaction",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_trade",
                to="accounting.ledgertransaction",
            ),
        ),
    ]
