# Generated by Django 6.1 on 2026-08-23 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0031_pablesite_policy_transition_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("underlying_name", models.CharField(max_length=160)),
                ("underlying_identifier", models.CharField(blank=True, default="", max_length=64)),
                ("match_key", models.CharField(editable=False, max_length=192)),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("equity", "Renta variable"),
                            ("fixed_income", "Renta fija"),
                            ("real_estate", "Inmobiliario"),
                            ("private_debt", "Deuda privada"),
                            ("commodities", "Materias primas"),
                            ("private_equity", "Capital privado"),
                            ("crypto", "Criptoactivos"),
                            ("cash", "Liquidez"),
                            ("trading", "Trading"),
                            ("other", "Otros"),
                            ("unclassified", "Sin clasificar"),
                        ],
                        max_length=24,
                    ),
                ),
                ("geography", models.CharField(blank=True, default="", max_length=32)),
                ("sector", models.CharField(blank=True, default="", max_length=32)),
                ("percent", models.DecimalField(decimal_places=3, max_digits=6)),
                ("observed_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holdings",
                        to="portfolio.portfolioposition",
                    ),
                ),
            ],
            options={
                "ordering": ["position_id", "-observed_on", "-percent", "underlying_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("position", "match_key", "observed_on"),
                        name="portfolio_holding_snapshot_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("percent__gt", 0), ("percent__lte", 100)),
                        name="portfolio_holding_percent_range",
                    ),
                ],
            },
        ),
    ]
