# Generated by Django 6.1 on 2026-08-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0032_positionholding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positionexposure",
            name="bucket",
            field=models.CharField(
                choices=[
                    ("north_america", "Norteamérica"),
                    ("europe", "Europa"),
                    ("spain", "España"),
                    ("japan", "Japón"),
                    ("asia_pacific", "Asia-Pacífico"),
                    ("emerging", "Emergentes"),
                    ("global", "Global"),
                    ("technology", "Tecnología"),
                    ("financials", "Financiero"),
                    ("health_care", "Salud"),
                    ("consumer_discretionary", "Consumo discrecional"),
                    ("consumer_staples", "Consumo básico"),
                    ("industrials", "Industrial"),
                    ("energy", "Energía"),
                    ("materials", "Materiales"),
                    ("utilities", "Servicios públicos"),
                    ("real_estate_sector", "Inmobiliario"),
                    ("communication", "Comunicación"),
                    ("index_fund", "Fondo indexado"),
                    ("active_fund", "Fondo activo"),
                    ("etf", "ETF"),
                    ("pension_plan", "Plan de pensiones"),
                    ("direct_equity", "Acciones directas"),
                    ("crowdfunding", "Crowdfunding"),
                    ("crowdlending", "Crowdlending"),
                    ("crypto", "Criptoactivo"),
                    ("deposit", "Depósito"),
                    ("other", "Otros"),
                ],
                max_length=32,
            ),
        ),
    ]
