# Generated by Django 6.1 on 2026-09-27

from decimal import Decimal

from django.db import migrations


def backfill_initial_zero_valuations(apps, schema_editor):
    PortfolioPosition = apps.get_model("portfolio", "PortfolioPosition")
    PositionValuation = apps.get_model("portfolio", "PositionValuation")

    for position in PortfolioPosition.objects.select_related("asset").filter(asset__amount=0):
        if PositionValuation.objects.filter(position_id=position.id).exists():
            continue
        PositionValuation.objects.create(
            position_id=position.id,
            valuation_date=position.opened_on,
            value=Decimal("0"),
            currency=position.asset.currency,
            source="manual",
            note="Valor inicial cero declarado al crear el activo.",
        )


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0033_alter_positionexposure_bucket"),
    ]

    operations = [
        migrations.RunPython(backfill_initial_zero_valuations, migrations.RunPython.noop),
    ]
