# Generated by Django 6.0.7 on 2026-08-03 20:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0006_familymember_plan_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnershipAllocationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fiscal_year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("window_start", models.DateField()),
                ("window_end", models.DateField()),
                ("base_currency", models.CharField(max_length=3)),
                ("source_hash", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ready", "Listo"),
                            ("provisional", "Provisional"),
                            ("blocked", "Bloqueado"),
                        ],
                        max_length=16,
                    ),
                ),
                ("quality_reasons", models.JSONField(blank=True, default=list)),
                ("observed_months", models.PositiveSmallIntegerField(default=0)),
                ("eligible_transaction_count", models.PositiveIntegerField(default=0)),
                ("excluded_transaction_count", models.PositiveIntegerField(default=0)),
                (
                    "total_qualifying_income",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("is_frozen", models.BooleanField(default=False)),
                ("frozen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-fiscal_year", "-month", "id"],
            },
        ),
        migrations.CreateModel(
            name="OwnershipAllocationSnapshotShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "qualifying_income",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["member_id"],
            },
        ),
        migrations.CreateModel(
            name="OwnershipIncomeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("category_key", models.CharField(max_length=64)),
                ("subcategory_key", models.CharField(blank=True, default="", max_length=64)),
            ],
            options={
                "ordering": ["category_key", "subcategory_key", "id"],
            },
        ),
        migrations.AddField(
            model_name="ownership",
            name="allocation_basis",
            field=models.CharField(
                choices=[
                    ("explicit_split", "Reparto explicito"),
                    ("recurring_income_12m", "Ingresos recurrentes (12 meses)"),
                ],
                default="explicit_split",
                max_length=32,
            ),
        ),
        migrations.AddConstraint(
            model_name="ownership",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind", "shared"),
                    models.Q(("allocation_basis", "explicit_split"), ("kind", "individual")),
                    _connector="OR",
                ),
                name="ownership_dynamic_requires_shared_memberships",
            ),
        ),
        migrations.AddField(
            model_name="ownershipallocationsnapshot",
            name="ownership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocation_snapshots",
                to="memberships.ownership",
            ),
        ),
        migrations.AddField(
            model_name="ownershipallocationsnapshotshare",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocation_snapshot_shares",
                to="memberships.familymember",
            ),
        ),
        migrations.AddField(
            model_name="ownershipallocationsnapshotshare",
            name="snapshot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shares",
                to="memberships.ownershipallocationsnapshot",
            ),
        ),
        migrations.AddField(
            model_name="ownershipincomerule",
            name="ownership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="income_rules",
                to="memberships.ownership",
            ),
        ),
        migrations.AddIndex(
            model_name="ownershipallocationsnapshot",
            index=models.Index(
                fields=["ownership", "fiscal_year", "month"], name="member_alloc_period_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownershipallocationsnapshot",
            constraint=models.UniqueConstraint(
                fields=("ownership", "fiscal_year", "month"),
                name="uniq_allocation_snapshot_month_memberships",
            ),
        ),
        migrations.AddConstraint(
            model_name="ownershipallocationsnapshotshare",
            constraint=models.UniqueConstraint(
                fields=("snapshot", "member"), name="uniq_allocation_share_member_memberships"
            ),
        ),
        migrations.AddConstraint(
            model_name="ownershipincomerule",
            constraint=models.UniqueConstraint(
                fields=("ownership", "category_key", "subcategory_key"),
                name="uniq_income_rule_per_ownership_memberships",
            ),
        ),
    ]
