# Generated by Django 5.2.15 on 2026-07-10 19:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("housing", "Vivienda"),
                            ("vehicle", "Vehiculo"),
                            ("studies", "Estudios"),
                            ("renovation", "Reforma"),
                            ("sabbatical", "Excedencia"),
                            ("reduced_hours", "Reduccion de jornada"),
                            ("business", "Negocio"),
                            ("debt_payoff", "Amortizacion de deuda"),
                            ("generic", "Generico"),
                        ],
                        default="generic",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("accepted", "Aceptado"),
                            ("discarded", "Descartado"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="plan.financialplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PlanEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("housing", "Vivienda"),
                            ("vehicle", "Vehiculo"),
                            ("studies", "Estudios"),
                            ("renovation", "Reforma"),
                            ("sabbatical", "Excedencia"),
                            ("reduced_hours", "Reduccion de jornada"),
                            ("business", "Negocio"),
                            ("debt_payoff", "Amortizacion de deuda"),
                            ("generic", "Generico"),
                        ],
                        max_length=32,
                    ),
                ),
                ("planned_date", models.DateField()),
                ("actual_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planificado"),
                            ("occurred", "Ocurrido"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("planned_impact_json", models.JSONField(blank=True, default=dict)),
                ("actual_impact_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="plan.financialplan",
                    ),
                ),
                (
                    "source_scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plan_events",
                        to="plan.scenario",
                    ),
                ),
            ],
            options={
                "ordering": ["planned_date", "id"],
            },
        ),
        migrations.AlterField(
            model_name="projectionsnapshot",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projection_snapshots",
                to="plan.scenario",
            ),
        ),
        migrations.CreateModel(
            name="ScenarioEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "initial_outflow",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "monthly_expense_delta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "monthly_income_delta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "monthly_contribution_delta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "new_asset_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "new_asset_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("productive", "Productivo"),
                            ("security", "Seguridad"),
                            ("short_term_goal", "Objetivo corto plazo"),
                            ("family_use", "Uso familiar"),
                            ("unknown", "Desconocido"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "new_debt_principal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "new_debt_interest_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("new_debt_term_months", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="plan.scenario",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="scenario",
            index=models.Index(fields=["plan", "status"], name="plan_scenar_plan_id_3017b9_idx"),
        ),
        migrations.AddIndex(
            model_name="scenario",
            index=models.Index(
                fields=["plan", "-created_at"], name="plan_scenar_plan_id_ea9910_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="planevent",
            index=models.Index(fields=["plan", "status"], name="plan_planev_plan_id_e7a457_idx"),
        ),
        migrations.AddIndex(
            model_name="planevent",
            index=models.Index(
                fields=["plan", "planned_date"], name="plan_planev_plan_id_63467a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scenarioevent",
            index=models.Index(
                fields=["scenario", "start_date"], name="plan_scenar_scenari_33409f_idx"
            ),
        ),
    ]
