# Generated by Django 5.2.15 on 2026-07-10 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0002_scenario_planevent_alter_projectionsnapshot_scenario_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Finding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("EMERGENCY_FUND_BELOW_TARGET", "Fondo de emergencia bajo objetivo"),
                            ("NEGATIVE_CASH_FLOW", "Flujo de caja negativo"),
                            ("HIGH_COST_DEBT", "Deuda cara"),
                            ("RETIREMENT_TARGET_OFF_TRACK", "Objetivo principal desviado"),
                            ("SECONDARY_GOAL_UNDERFUNDED", "Objetivo secundario infrafinanciado"),
                            ("PRODUCTIVE_CAPITAL_STAGNANT", "Capital productivo estancado"),
                            ("DATA_INCOMPLETE", "Datos incompletos"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informativo"),
                            ("warning", "Atencion"),
                            ("critical", "Critico"),
                        ],
                        max_length=16,
                    ),
                ),
                ("period", models.CharField(max_length=16)),
                ("evidence_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierto"),
                            ("resolved", "Resuelto"),
                            ("dismissed", "Descartado"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="plan.financialplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("REBUILD_EMERGENCY_FUND", "Reconstruir fondo"),
                            ("REDUCE_HIGH_COST_DEBT", "Reducir deuda cara"),
                            ("INCREASE_CONTRIBUTION", "Aumentar aportacion"),
                            ("ADJUST_TARGET_DATE", "Ajustar fecha objetivo"),
                            ("ADJUST_TARGET_INCOME", "Ajustar nivel de vida"),
                            ("RESCHEDULE_SECONDARY_GOAL", "Reprogramar objetivo"),
                            ("REDUCE_EVENT_OUTFLOW", "Reducir desembolso"),
                            ("COMPLETE_DATA", "Completar datos"),
                        ],
                        max_length=64,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("action_json", models.JSONField(blank=True, default=dict)),
                ("impact_json", models.JSONField(blank=True, default=dict)),
                ("alternatives_json", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Abierta"),
                            ("accepted", "Aceptada"),
                            ("dismissed", "Descartada"),
                            ("snoozed", "Pospuesta"),
                        ],
                        default="open",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "finding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="plan.finding",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["plan", "status"], name="plan_findin_plan_id_db9db7_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["plan", "period"], name="plan_findin_plan_id_6bcf39_idx"),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                fields=("plan", "code", "period"), name="uniq_finding_period"
            ),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["finding", "status"], name="plan_recomm_finding_216419_idx"),
        ),
        migrations.AddIndex(
            model_name="recommendation",
            index=models.Index(fields=["status", "priority"], name="plan_recomm_status_f15958_idx"),
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.UniqueConstraint(
                fields=("finding", "code"), name="uniq_recommendation_finding_code"
            ),
        ),
    ]
