# Generated by Django 5.2.15 on 2026-07-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0003_finding_recommendation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planevent",
            name="effective_end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
