# Generated by Django 5.2.15 on 2026-07-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("net_worth", "0042_remove_legacy_contribution_fields"),
        ("plan", "0004_planevent_effective_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="planevent",
            name="linked_assets",
            field=models.ManyToManyField(
                blank=True, related_name="plan_events", to="net_worth.asset"
            ),
        ),
        migrations.AddField(
            model_name="planevent",
            name="linked_liabilities",
            field=models.ManyToManyField(
                blank=True, related_name="plan_events", to="net_worth.liability"
            ),
        ),
    ]
