# Generated by Django 5.2.15 on 2026-07-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0005_planevent_linked_assets_planevent_linked_liabilities"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recommendation",
            name="code",
            field=models.CharField(
                choices=[
                    ("REBUILD_EMERGENCY_FUND", "Reconstruir fondo"),
                    ("REDUCE_HIGH_COST_DEBT", "Reducir deuda cara"),
                    ("INCREASE_CONTRIBUTION", "Aumentar aportación"),
                    ("ADJUST_TARGET_DATE", "Ajustar fecha objetivo"),
                    ("ADJUST_TARGET_INCOME", "Ajustar nivel de vida"),
                    ("RESCHEDULE_SECONDARY_GOAL", "Reprogramar objetivo"),
                    ("REDUCE_EVENT_OUTFLOW", "Reducir desembolso"),
                    ("COMPLETE_DATA", "Completar datos"),
                ],
                max_length=64,
            ),
        ),
    ]
