# Generated by Django 5.2.16 on 2026-07-26 09:31

import django.db.models.deletion
from django.db import migrations, models


def backfill_source_recommendation(apps, schema_editor):
    Scenario = apps.get_model("plan", "Scenario")
    ScenarioEvent = apps.get_model("plan", "ScenarioEvent")
    for event in ScenarioEvent.objects.exclude(metadata_json={}):
        recommendation_id = (event.metadata_json or {}).get("source_recommendation")
        if recommendation_id:
            Scenario.objects.filter(
                id=event.scenario_id,
                source_recommendation__isnull=True,
            ).update(source_recommendation_id=recommendation_id)


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0006_alter_recommendation_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendation",
            name="snoozed_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="source_recommendation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scenarios",
                to="plan.recommendation",
            ),
        ),
        migrations.AddField(
            model_name="scenarioevent",
            name="monthly_contribution_destination",
            field=models.CharField(
                choices=[
                    ("productive", "Capital productivo"),
                    ("security", "Capital de seguridad"),
                    ("debt", "Reduccion de deuda"),
                ],
                default="productive",
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_source_recommendation, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="recommendation",
            name="code",
            field=models.CharField(
                choices=[
                    ("REBUILD_EMERGENCY_FUND", "Reconstruir fondo"),
                    ("REDUCE_HIGH_COST_DEBT", "Reducir deuda cara"),
                    ("INCREASE_CONTRIBUTION", "Aumentar aportación"),
                    ("ADJUST_TARGET_DATE", "Ajustar fecha objetivo"),
                    ("ADJUST_TARGET_INCOME", "Ajustar nivel de vida"),
                    ("RESCHEDULE_SECONDARY_GOAL", "Reprogramar objetivo"),
                    ("REDUCE_EVENT_OUTFLOW", "Reducir desembolso"),
                    ("COMPLETE_DATA", "Completar datos"),
                    ("RESTORE_CASH_FLOW", "Recuperar flujo de caja"),
                ],
                max_length=64,
            ),
        ),
    ]
