# Generated by Django 6.0.7 on 2026-07-31 08:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0007_recommendation_snoozed_until_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assumptionset",
            name="security_contribution_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.2500"),
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="assumptionset",
            name="security_target_expense_years",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2.00"),
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
