# Generated by Django 6.0.7 on 2026-07-31 08:50

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plan", "0008_assumptionset_security_contribution_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assumptionset",
            name="furnishings_depreciation_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.1200"),
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
    ]
