# Generated by Django 6.0.7 on 2026-08-14 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memberships", "0007_ownershipallocationsnapshot_and_more"),
        ("plan", "0010_backfill_planned_decision_financing"),
    ]

    operations = [
        migrations.AddField(
            model_name="planevent",
            name="ownership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plan_events",
                to="memberships.ownership",
            ),
        ),
    ]
