# Generated by Django 5.2.11 on 2026-02-20 22:13

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("net_worth", "0012_remove_ownershipsplit_member_remove_ownership_member_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Fecha de inicio o adquisicion del activo.",
            ),
        ),
        migrations.AddField(
            model_name="liability",
            name="annual_interest_tae",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="TAE anual en porcentaje. En esta iteracion se modela como tipo fijo para hipoteca, prestamo personal y tarjeta.",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="liability",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="Fecha de inicio o adquisicion del pasivo.",
            ),
        ),
    ]
