# Generated by Django 5.2.11 on 2026-02-22 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("net_worth", "0014_asset_annual_interest_tae"),
    ]

    operations = [
        migrations.AddField(
            model_name="liability",
            name="monthly_payment_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Cuota mensual manual en la moneda del pasivo. Temporal hasta modelar amortizacion y calendario.",
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
