# Generated by Django 5.2.11 on 2026-02-25 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("net_worth", "0018_remove_liability_monthly_payment_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiquidityMonthlyCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fiscal_year", models.PositiveSmallIntegerField(default=2026)),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("confirmed", "Confirmado"), ("adjusted", "Ajustado")],
                        default="confirmed",
                        max_length=16,
                    ),
                ),
                ("closing_balance_real", models.DecimalField(decimal_places=8, max_digits=20)),
                ("note", models.CharField(blank=True, default="", max_length=240)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidity_monthly_checkins",
                        to="net_worth.asset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liquidity_monthly_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fiscal_year", "-month", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "fiscal_year", "month"], name="nw_liq_chk_user_ym_idx"
                    ),
                    models.Index(fields=["asset"], name="nw_liq_chk_asset_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "asset", "fiscal_year", "month"),
                        name="unique_liq_checkin_user_asset_year_month",
                    )
                ],
            },
        ),
    ]
