# Generated by Django 5.2.11 on 2026-03-05 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("net_worth", "0024_assetimprovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="expected_end_date",
            field=models.DateField(
                blank=True,
                help_text="Fecha fin prevista para aportaciones periodicas en inversiones. Solo aplica cuando investment_contribution_mode=periodic_contribution.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="investment_contribution_mode",
            field=models.CharField(
                choices=[
                    ("one_time", "Aportacion unica"),
                    ("periodic_contribution", "Aportacion periodica"),
                ],
                default="one_time",
                help_text="Modo de aportacion para inversiones: unica o periodica. Solo aplica a category=investments.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="monthly_contribution_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Cuota mensual prevista para inversiones periodicas. Solo aplica a investment_contribution_mode=periodic_contribution.",
                max_digits=20,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="valuation_model",
            field=models.CharField(
                choices=[("manual", "Manual"), ("real_estate_auto", "Vivienda automatica")],
                default="manual",
                help_text="Modelo de valoracion del activo. En inmuebles residenciales puede usarse valoracion automatica por suelo + construccion.",
                max_length=24,
            ),
        ),
    ]
