# Generated by Django 5.2.11 on 2026-03-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("net_worth", "0034_liabilityevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liquiditymonthlycheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmado"),
                    ("adjusted", "Ajustado"),
                    ("estimated", "Estimado"),
                ],
                default="confirmed",
                max_length=16,
            ),
        ),
    ]
