# Generated by Django 5.2.11 on 2026-03-26 21:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net_worth', '0037_delete_networthsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentContributionInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('frequency', models.CharField(choices=[('monthly', 'Mensual'), ('weekly', 'Semanal')], default='monthly', max_length=20)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_intervals', to='net_worth.asset')),
            ],
            options={
                'ordering': ['start_date', 'id'],
            },
        ),
    ]
