# Generated by Django 5.2.15 on 2026-07-12 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("net_worth", "0042_remove_legacy_contribution_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assetimprovement",
            name="annual_interest_tae",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="TAE anual asociada a la financiación de la reforma (opcional).",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
