# Generated by Django 5.2.11 on 2026-02-20 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0002_annualincomeentry_fiscal_year"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnualExpenseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("savings_allocation", "Ahorro"),
                            ("financial_investments", "Inversion financiera"),
                            ("real_estate_assets", "Activos inmobiliarios"),
                            ("tangible_assets", "Activos mobiliarios"),
                            ("consumption_expenses", "Gasto puro y duro"),
                        ],
                        max_length=32,
                    ),
                ),
                ("subcategory", models.CharField(max_length=64)),
                ("owner_name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "expense_type",
                    models.CharField(
                        choices=[("recurrent", "Recurrente"), ("one_off", "Puntual")],
                        default="recurrent",
                        max_length=16,
                    ),
                ),
                ("amount_annual", models.DecimalField(decimal_places=2, max_digits=14)),
                ("fiscal_year", models.PositiveSmallIntegerField(default=2026)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("notes", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_expense_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_annualexpenseentry",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"], name="core_annual_user_id_81e145_idx"
                    ),
                    models.Index(fields=["user", "fiscal_year"], name="budget_ae_user_year_idx"),
                    models.Index(
                        fields=["user", "category"], name="core_annual_user_id_e2d1b1_idx"
                    ),
                    models.Index(
                        fields=["user", "subcategory"], name="core_annual_user_id_d985ed_idx"
                    ),
                ],
            },
        ),
    ]
