# Generated by Django 5.2.11 on 2026-02-25 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0006_annualexpenseentry_generated_from_liability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="annualexpenseentry",
            name="target_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AnnualExpenseMonthlyCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fiscal_year", models.PositiveSmallIntegerField(default=2026)),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("confirmed", "Confirmado"),
                            ("adjusted", "Ajustado"),
                            ("skipped", "No ocurrido"),
                        ],
                        default="confirmed",
                        max_length=16,
                    ),
                ),
                (
                    "executed_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("note", models.CharField(blank=True, default="", max_length=240)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "annual_expense_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_checkins",
                        to="budget.annualexpenseentry",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_expense_monthly_checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_annualexpensemonthlycheckin",
                "ordering": ["-fiscal_year", "-month", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "fiscal_year", "month"], name="budget_aemc_user_ym_idx"
                    ),
                    models.Index(fields=["annual_expense_entry"], name="budget_aemc_entry_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "annual_expense_entry", "fiscal_year", "month"),
                        name="budget_aemc_unique_user_entry_year_month",
                    )
                ],
            },
        ),
    ]
