# Generated by Django 5.2.11 on 2026-02-25 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_annualexpenseentry_target_month_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualIncomeMonthlyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.PositiveSmallIntegerField(default=2026)),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmado'), ('adjusted', 'Ajustado'), ('skipped', 'No ocurrido')], default='confirmed', max_length=16)),
                ('executed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=240)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_income_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_checkins', to='budget.annualincomeentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_income_monthly_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_annualincomemonthlycheckin',
                'ordering': ['-fiscal_year', '-month', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'fiscal_year', 'month'], name='budget_aimc_user_ym_idx'), models.Index(fields=['annual_income_entry'], name='budget_aimc_entry_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'annual_income_entry', 'fiscal_year', 'month'), name='budget_aimc_unique_user_entry_year_month')],
            },
        ),
    ]
