# Generated by Django 5.2.11 on 2026-03-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_annualexpenseentry_source_asset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualexpenseentry',
            name='term_end_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annualincomeentry',
            name='term_end_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
