# Generated by Django 5.2.11 on 2026-03-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0010_annualentry_term_end_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualexpenseentry",
            name="amount_input_period",
            field=models.CharField(
                choices=[("annual", "Anual"), ("monthly", "Mensual")],
                default="annual",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="annualincomeentry",
            name="amount_input_period",
            field=models.CharField(
                choices=[("annual", "Anual"), ("monthly", "Mensual")],
                default="annual",
                max_length=8,
            ),
        ),
    ]
