# Generated by Django 5.2.11 on 2026-03-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0011_annualentry_amount_input_period"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualincomeentry",
            name="target_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
