# Generated by Django 5.2.11 on 2026-03-19 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0012_annualincomeentry_target_month"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualexpensemonthlycheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmado"),
                    ("adjusted", "Ajustado"),
                    ("skipped", "No ocurrido"),
                    ("estimated", "Estimado"),
                ],
                default="confirmed",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="annualincomemonthlycheckin",
            name="status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmado"),
                    ("adjusted", "Ajustado"),
                    ("skipped", "No ocurrido"),
                    ("estimated", "Estimado"),
                ],
                default="confirmed",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="MonthlyClose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fiscal_year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Borrador"),
                            ("finalized", "Finalizado"),
                            ("locked", "Bloqueado"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "income_total_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "expense_total_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                (
                    "liquidity_total_snapshot",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_closes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "core_monthlyclose",
                "ordering": ["-fiscal_year", "-month"],
                "indexes": [
                    models.Index(
                        fields=["user", "fiscal_year", "month"], name="budget_mc_user_ym_idx"
                    ),
                    models.Index(fields=["user", "status"], name="budget_mc_user_status_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "fiscal_year", "month"),
                        name="budget_mc_unique_user_year_month",
                    )
                ],
            },
        ),
    ]
