# Generated by Django 5.2.15 on 2026-07-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0014_alter_annualexpenseentry_cashflow_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annualexpenseentry",
            name="term_start_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annualincomeentry",
            name="term_start_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
