# Generated by Django 6.0.7 on 2026-08-03 21:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0016_reclassify_system_generated_commitments"),
        ("memberships", "0007_ownershipallocationsnapshot_and_more"),
        ("net_worth", "0043_alter_assetimprovement_annual_interest_tae"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="annualexpenseentry",
            name="ownership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annual_expense_entries",
                to="memberships.ownership",
            ),
        ),
        migrations.AddField(
            model_name="annualincomeentry",
            name="ownership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="annual_income_entries",
                to="memberships.ownership",
            ),
        ),
        migrations.CreateModel(
            name="SettlementAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("operating", "Operativa"),
                            ("personal_destination", "Destino personal"),
                            ("allocation_destination", "Destino de asignacion"),
                            ("physical_cash", "Efectivo fisico"),
                        ],
                        max_length=32,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "accepted_physical_balance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "modeled_balance_at_activation",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_accounts",
                        to="net_worth.asset",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_accounts",
                        to="memberships.familymember",
                    ),
                ),
            ],
            options={
                "db_table": "budget_settlement_account",
                "ordering": ["role", "asset_id"],
            },
        ),
        migrations.AddField(
            model_name="annualexpenseentry",
            name="settlement_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="annual_expense_entries",
                to="budget.settlementaccount",
            ),
        ),
        migrations.CreateModel(
            name="SettlementProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("activation_date", models.DateField(blank=True, null=True)),
                ("base_currency", models.CharField(default="EUR", max_length=3)),
                (
                    "readiness_status",
                    models.CharField(
                        choices=[
                            ("not_checked", "No comprobado"),
                            ("ready", "Listo"),
                            ("blocked", "Bloqueado"),
                        ],
                        default="not_checked",
                        max_length=16,
                    ),
                ),
                ("readiness_checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "budget_settlement_profile",
            },
        ),
        migrations.CreateModel(
            name="SettlementOpeningAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("wallet_normalization", "Normalizacion de monedero"),
                        ],
                        default="manual",
                        max_length=24,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_adjustments",
                        to="budget.settlementaccount",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_opening_adjustments",
                        to="memberships.familymember",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_adjustments",
                        to="budget.settlementprofile",
                    ),
                ),
            ],
            options={
                "db_table": "budget_settlement_opening_adjustment",
                "ordering": ["account_id", "member_id", "id"],
            },
        ),
        migrations.AddField(
            model_name="settlementaccount",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="budget.settlementprofile",
            ),
        ),
        migrations.CreateModel(
            name="SettlementOpeningBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_balances",
                        to="budget.settlementaccount",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_opening_balances",
                        to="memberships.familymember",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_balances",
                        to="budget.settlementprofile",
                    ),
                ),
            ],
            options={
                "db_table": "budget_settlement_opening_balance",
                "ordering": ["account_id", "member_id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "account", "member"),
                        name="budget_settle_opening_account_member_unique",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="settlementaccount",
            constraint=models.UniqueConstraint(
                fields=("profile", "asset"), name="budget_settle_account_asset_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True), ("role", "personal_destination")),
                fields=("profile", "member", "currency"),
                name="budget_settle_primary_member_currency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlementaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("member__isnull", False), ("role", "personal_destination")),
                    models.Q(
                        models.Q(("role", "personal_destination"), _negated=True),
                        ("member__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="budget_settle_personal_requires_member",
            ),
        ),
    ]
