# Generated by Django 6.0.7 on 2026-08-03 21:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0017_annualexpenseentry_ownership_and_more"),
        ("memberships", "0007_ownershipallocationsnapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ready", "Listo"), ("not_ready", "No listo")], max_length=16
                    ),
                ),
                ("base_currency", models.CharField(max_length=3)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("target_year", models.PositiveSmallIntegerField()),
                (
                    "target_month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                ("opening_source", models.CharField(max_length=24)),
                ("source_hash", models.CharField(max_length=64)),
                ("allocations", models.JSONField(default=list)),
                ("economic_balances", models.JSONField(default=list)),
                ("account_balances", models.JSONField(default=list)),
                ("reserves", models.JSONField(default=list)),
                ("compensations", models.JSONField(default=list)),
                ("blockers", models.JSONField(default=list)),
                ("warnings", models.JSONField(default=list)),
                ("reconciliation", models.JSONField(default=dict)),
                ("is_frozen", models.BooleanField(default=True)),
                ("computed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "allocation_snapshots",
                    models.ManyToManyField(
                        blank=True,
                        related_name="settlement_snapshots",
                        to="memberships.ownershipallocationsnapshot",
                    ),
                ),
                (
                    "monthly_close",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_snapshot",
                        to="budget.monthlyclose",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="snapshots",
                        to="budget.settlementprofile",
                    ),
                ),
            ],
            options={
                "db_table": "budget_settlement_snapshot",
                "ordering": ["-monthly_close__fiscal_year", "-monthly_close__month"],
            },
        ),
        migrations.CreateModel(
            name="SettlementTransferRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("reason", models.CharField(default="settlement", max_length=32)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "from_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_recommendations",
                        to="budget.settlementaccount",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_recommendations",
                        to="memberships.familymember",
                    ),
                ),
                (
                    "ownership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlement_recommendations",
                        to="memberships.ownership",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="budget.settlementsnapshot",
                    ),
                ),
                (
                    "to_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_recommendations",
                        to="budget.settlementaccount",
                    ),
                ),
            ],
            options={
                "db_table": "budget_settlement_transfer_recommendation",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
