# Generated by Django 6.0.7 on 2026-08-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0018_settlementsnapshot_settlementtransferrecommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlementtransferrecommendation",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="settlementtransferrecommendation",
            name="applied_amount",
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name="settlementtransferrecommendation",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="settlementtransferrecommendation",
            name="status",
            field=models.CharField(
                choices=[
                    ("recommended", "Recomendada"),
                    ("accepted", "Aceptada"),
                    ("applied", "Aplicada"),
                    ("partially_applied", "Aplicada parcialmente"),
                    ("cancelled", "Cancelada"),
                ],
                default="recommended",
                max_length=24,
            ),
        ),
    ]
