# Generated by Django 6.0.7 on 2026-08-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0019_settlementtransferrecommendation_accepted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monthlyclose",
            name="expected_liquidity_total_snapshot",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="monthlyclose",
            name="opening_liquidity_snapshot",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="monthlyclose",
            name="residual_snapshot",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
