# Generated by Django 6.1 on 2026-08-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget", "0023_settlementwalletnormalization"),
    ]

    operations = [
        migrations.AddField(
            model_name="settlementprofile",
            name="operating_reserve_adjustment",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Ajuste manual, positivo o negativo, sobre la reserva operativa calculada.",
                max_digits=14,
            ),
        ),
    ]
