# Generated by Django 6.1.1 on 2026-09-30 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounting", "0013_ledgertransaction_fee_for"),
        ("budget", "0024_settlementprofile_operating_reserve_adjustment"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementWalletSweep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "monthly_close",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_wallet_sweeps",
                        to="budget.monthlyclose",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_sweeps",
                        to="budget.settlementprofile",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_wallet_sweep",
                        to="accounting.ledgertransaction",
                    ),
                ),
            ],
            options={
                "db_table": "budget_settlement_wallet_sweep",
                "ordering": ["transaction__booking_date", "transaction_id"],
            },
        ),
    ]
