# Generated by Django 5.2.13 on 2026-04-22 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("memberships", "0005_rename_familymember_unique_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "broker",
                    models.CharField(
                        choices=[("pionex", "Pionex"), ("binance", "Binance")], max_length=20
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("api_key", models.CharField(max_length=200)),
                ("api_secret_encrypted", models.BinaryField()),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_stats", models.JSONField(blank=True, default=dict)),
                ("last_sync_gaps", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ownership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_credentials",
                        to="memberships.ownership",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BotNetResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bot_id", models.CharField(max_length=100)),
                ("bot_type", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=200)),
                ("base_asset", models.CharField(max_length=10)),
                ("quote_asset", models.CharField(max_length=10)),
                ("realized_profit", models.DecimalField(decimal_places=10, max_digits=24)),
                (
                    "total_fee_base",
                    models.DecimalField(decimal_places=10, default=0, max_digits=24),
                ),
                (
                    "total_fee_quote",
                    models.DecimalField(decimal_places=10, default=0, max_digits=24),
                ),
                ("period_start", models.DateTimeField()),
                ("period_end", models.DateTimeField()),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_results",
                        to="broker_integrations.brokercredential",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "-id"],
            },
        ),
        migrations.CreateModel(
            name="BrokerTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pionex_api", "Pionex API"),
                            ("pionex_csv", "Pionex CSV"),
                            ("binance_api", "Binance API"),
                            ("binance_csv", "Binance CSV"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trade_id", models.CharField(max_length=100)),
                ("symbol", models.CharField(max_length=20)),
                ("base_asset", models.CharField(max_length=10)),
                ("quote_asset", models.CharField(max_length=10)),
                (
                    "side",
                    models.CharField(choices=[("BUY", "BUY"), ("SELL", "SELL")], max_length=4),
                ),
                ("price", models.DecimalField(decimal_places=10, max_digits=24)),
                ("quantity", models.DecimalField(decimal_places=10, max_digits=24)),
                ("fee", models.DecimalField(decimal_places=10, default=0, max_digits=24)),
                ("fee_asset", models.CharField(blank=True, default="", max_length=10)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="broker_integrations.brokercredential",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp", "id"],
            },
        ),
        migrations.CreateModel(
            name="FuturesPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("pionex_api", "Pionex API"), ("pionex_csv", "Pionex CSV")],
                        max_length=20,
                    ),
                ),
                ("position_id", models.CharField(max_length=200)),
                ("symbol", models.CharField(max_length=30)),
                ("base_asset", models.CharField(max_length=10)),
                (
                    "side",
                    models.CharField(choices=[("long", "Long"), ("short", "Short")], max_length=10),
                ),
                ("open_time", models.DateTimeField()),
                ("close_time", models.DateTimeField()),
                ("pnl", models.DecimalField(decimal_places=10, max_digits=24)),
                ("fee", models.DecimalField(decimal_places=10, default=0, max_digits=24)),
                ("funding_fee", models.DecimalField(decimal_places=10, default=0, max_digits=24)),
                ("net_pnl", models.DecimalField(decimal_places=10, max_digits=24)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="futures_positions",
                        to="broker_integrations.brokercredential",
                    ),
                ),
            ],
            options={
                "ordering": ["close_time", "id"],
            },
        ),
        migrations.CreateModel(
            name="IncomeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pionex_staking_api", "Pionex Staking API"),
                            ("pionex_staking_csv", "Pionex Staking CSV"),
                            ("pionex_dual_invest_api", "Pionex Dual Invest API"),
                            ("pionex_commission_csv", "Pionex Commission CSV"),
                            ("binance_earn_api", "Binance Earn API"),
                            ("binance_earn_csv", "Binance Earn CSV"),
                            ("binance_referral_csv", "Binance Referral CSV"),
                            ("manual", "Manual"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "income_type",
                    models.CharField(
                        choices=[
                            ("earn_issued", "Earn Issued"),
                            ("earn_claimed", "Earn Claimed"),
                            ("dual_invest_yield", "Dual Invest Yield"),
                            ("commission", "Commission"),
                            ("binance_earn", "Binance Earn"),
                        ],
                        max_length=30,
                    ),
                ),
                ("asset", models.CharField(max_length=10)),
                ("amount", models.DecimalField(decimal_places=10, max_digits=24)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("description", models.CharField(blank=True, default="", max_length=300)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="income_events",
                        to="broker_integrations.brokercredential",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="brokercredential",
            index=models.Index(fields=["user", "broker"], name="broker_inte_user_id_ebf9fa_idx"),
        ),
        migrations.AddIndex(
            model_name="brokercredential",
            index=models.Index(fields=["ownership"], name="broker_inte_ownersh_705c07_idx"),
        ),
        migrations.AddConstraint(
            model_name="brokercredential",
            constraint=models.UniqueConstraint(
                fields=("user", "broker", "label"), name="uniq_broker_credential_label_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="botnetresult",
            constraint=models.UniqueConstraint(
                fields=("credential", "bot_id"), name="uniq_bot_result_credential_bot_id"
            ),
        ),
        migrations.AddIndex(
            model_name="brokertrade",
            index=models.Index(
                fields=["source", "timestamp"], name="broker_inte_source_184ad4_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="brokertrade",
            constraint=models.UniqueConstraint(
                fields=("source", "trade_id"), name="uniq_broker_trade_source_trade_id"
            ),
        ),
        migrations.AddIndex(
            model_name="futuresposition",
            index=models.Index(
                fields=["source", "close_time"], name="broker_inte_source_df1a97_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="futuresposition",
            constraint=models.UniqueConstraint(
                fields=("source", "position_id"), name="uniq_futures_position_source_position_id"
            ),
        ),
        migrations.AddIndex(
            model_name="incomeevent",
            index=models.Index(
                fields=["source", "timestamp"], name="broker_inte_source_951203_idx"
            ),
        ),
    ]
