# Generated by Django 5.2.13 on 2026-04-24 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker_integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokertrade",
            name="bot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fills",
                to="broker_integrations.botnetresult",
            ),
        ),
        migrations.AlterField(
            model_name="brokertrade",
            name="source",
            field=models.CharField(
                choices=[
                    ("pionex_api", "Pionex API"),
                    ("pionex_bot_api", "Pionex Bot API"),
                    ("pionex_csv", "Pionex CSV"),
                    ("binance_api", "Binance API"),
                    ("binance_csv", "Binance CSV"),
                ],
                max_length=20,
            ),
        ),
    ]
