# Generated by Django 5.2.13 on 2026-04-24 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker_integrations", "0002_brokertrade_bot_alter_brokertrade_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrokerSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("year", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("ok", "OK"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("stats", models.JSONField(blank=True, default=dict)),
                ("gaps", models.JSONField(blank=True, default=list)),
                ("new_trade_ids", models.JSONField(blank=True, default=list)),
                ("updated_trade_ids", models.JSONField(blank=True, default=list)),
                ("new_income_event_ids", models.JSONField(blank=True, default=list)),
                ("updated_income_event_ids", models.JSONField(blank=True, default=list)),
                ("new_bot_result_ids", models.JSONField(blank=True, default=list)),
                ("updated_bot_result_ids", models.JSONField(blank=True, default=list)),
                (
                    "credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_runs",
                        to="broker_integrations.brokercredential",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["credential", "year", "started_at"],
                        name="broker_inte_credent_4d4ecb_idx",
                    )
                ],
            },
        ),
    ]
