# Generated by Django 5.2.13 on 2026-04-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker_integrations", "0003_brokersyncrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokertrade",
            name="eur_rate_source",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="brokertrade",
            name="fee_eur",
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name="brokertrade",
            name="price_eur",
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True),
        ),
        migrations.CreateModel(
            name="MarketRateSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pair", models.CharField(max_length=20)),
                (
                    "interval",
                    models.CharField(
                        choices=[("1m", "1m"), ("1h", "1h"), ("1d", "1d")], max_length=4
                    ),
                ),
                ("open_time", models.DateTimeField(db_index=True)),
                ("close", models.DecimalField(decimal_places=10, max_digits=24)),
                (
                    "high",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True),
                ),
                (
                    "low",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True),
                ),
                ("source", models.CharField(max_length=30)),
                ("raw", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["pair", "interval", "open_time", "id"],
                "indexes": [
                    models.Index(
                        fields=["pair", "interval", "open_time"], name="broker_inte_pair_0f6735_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("pair", "interval", "open_time"),
                        name="uniq_market_rate_snapshot_pair_interval_open_time",
                    )
                ],
            },
        ),
    ]
