# Generated by Django 5.2.13 on 2026-04-24 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker_integrations", "0004_brokertrade_eur_rate_source_brokertrade_fee_eur_and_more"),
        ("memberships", "0005_rename_familymember_unique_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualCostBasis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("asset", models.CharField(max_length=10)),
                ("quantity", models.DecimalField(decimal_places=10, max_digits=24)),
                ("quantity_remaining", models.DecimalField(decimal_places=10, max_digits=24)),
                ("acquired_at", models.DateTimeField()),
                ("cost_eur", models.DecimalField(decimal_places=10, max_digits=24)),
                ("exchange_origin", models.CharField(default="external", max_length=20)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ownership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_cost_basis_entries",
                        to="memberships.ownership",
                    ),
                ),
            ],
            options={
                "ordering": ["acquired_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["ownership", "asset", "acquired_at"],
                        name="broker_inte_ownersh_be3c69_idx",
                    )
                ],
            },
        ),
    ]
