# Generated by Django 5.2.13 on 2026-04-25 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("broker_integrations", "0005_manualcostbasis"),
    ]

    operations = [
        migrations.AddField(
            model_name="brokertrade",
            name="fiscal_identity_key",
            field=models.CharField(blank=True, db_index=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="brokertrade",
            name="fiscal_provenance",
            field=models.CharField(
                blank=True,
                choices=[("api", "API"), ("csv_fallback", "CSV Fallback")],
                default="",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="DepositWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("pionex_api", "Pionex API"),
                            ("pionex_csv", "Pionex CSV"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(max_length=200)),
                (
                    "direction",
                    models.CharField(
                        choices=[("deposit", "Deposit"), ("withdrawal", "Withdrawal")],
                        max_length=12,
                    ),
                ),
                ("asset", models.CharField(max_length=10)),
                ("amount", models.DecimalField(decimal_places=10, max_digits=24)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "cost_eur_per_unit",
                    models.DecimalField(blank=True, decimal_places=10, max_digits=24, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deposit_withdrawals",
                        to="broker_integrations.brokercredential",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp", "id"],
                "indexes": [
                    models.Index(
                        fields=["source", "timestamp"], name="broker_inte_source_12c5ff_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "transaction_id"),
                        name="uniq_deposit_withdrawal_source_transaction_id",
                    )
                ],
            },
        ),
    ]
