# Generated by Django 5.2.13 on 2026-04-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_integrations', '0006_brokertrade_fiscal_identity_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositwithdrawal',
            name='source',
            field=models.CharField(choices=[('pionex_api', 'Pionex API'), ('pionex_csv', 'Pionex CSV'), ('binance_csv', 'Binance CSV'), ('manual', 'Manual')], max_length=20),
        ),
    ]
