# Generated by Django 5.2.11 on 2026-03-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_move_annual_income_to_budget_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxrate',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fxrate',
            name='managed_by_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fxrate',
            name='source',
            field=models.CharField(default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='fxrate',
            name='source_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='inflationindex',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inflationindex',
            name='managed_by_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inflationindex',
            name='source',
            field=models.CharField(default='manual', max_length=32),
        ),
        migrations.AddField(
            model_name='inflationindex',
            name='source_key',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='inflationindex',
            name='period',
            field=models.DateField(help_text='Month of the index. Use YYYY-MM-01.'),
        ),
        migrations.AlterField(
            model_name='inflationindex',
            name='region',
            field=models.CharField(choices=[('ES', 'Espana'), ('ES-AN', 'Andalucia'), ('ES-AR', 'Aragon'), ('ES-AS', 'Asturias'), ('ES-IB', 'Illes Balears'), ('ES-CN', 'Canarias'), ('ES-CB', 'Cantabria'), ('ES-CL', 'Castilla y Leon'), ('ES-CM', 'Castilla-La Mancha'), ('ES-CT', 'Cataluna'), ('ES-VC', 'Comunitat Valenciana'), ('ES-EX', 'Extremadura'), ('ES-GA', 'Galicia'), ('ES-MD', 'Comunidad de Madrid'), ('ES-MC', 'Region de Murcia'), ('ES-NC', 'Comunidad Foral de Navarra'), ('ES-PV', 'Pais Vasco'), ('ES-RI', 'La Rioja'), ('ES-CE', 'Ceuta'), ('ES-ML', 'Melilla')], default='ES', max_length=10),
        ),
        migrations.CreateModel(
            name='MarketDataSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(choices=[('fx', 'FX'), ('inflation', 'Inflation')], max_length=32)),
                ('scope', models.CharField(max_length=64)),
                ('required_start_date', models.DateField(blank=True, null=True)),
                ('covered_until', models.DateField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['dataset', 'scope'],
                'indexes': [models.Index(fields=['dataset', 'scope'], name='core_market_dataset_4a4ae3_idx')],
                'constraints': [models.UniqueConstraint(fields=('dataset', 'scope'), name='unique_market_data_dataset_scope')],
            },
        ),
    ]
